<?php

/**
 * @file
 * Contains import_sunset_boulevard_products.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function import_sunset_boulevard_products_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the import_sunset_boulevard_products module.
    case 'help.page.import_sunset_boulevard_products':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Imports products from API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function import_sunset_boulevard_products_form_alter(&$form, &$form_state, $form_id) {

  switch($form_id) { 
  
    // Check both the cart and the checkout page
    case 'views_form_commerce_cart_form_default_1':
    case 'commerce_checkout_flow_multistep_default':

      print_r($form['edit-quantity-0']);
      $current_time = intval( date('Hm') );

      if( $current_time > 2200 || $current_time < 930 ) {

        $closing_text = 'The store opens again at 09:30am';

        $form['actions']['checkout']['#disabled'] = true;
        $form['actions']['checkout']['#value'] = $closing_text;
        $form['actions']['next']['#disabled'] = true;
        $form['actions']['next']['#value'] = $closing_text;

      }

      break;

  }

}